### ISSUE TITLE
No consigo que me funcione, se queda "esperando"

### ISSUE THREAD

**Issue by ubutfgm** [rogama25/UBUVoiceAssistant#26]
En primer lugar gracias por el instalador, se agradece.

Lamentablemente al tratar de conectar tras meter los datos de login se queda esperando y no llega a devolver nada.

```
▶ UBUVoiceAssistant
/home/alvar/anaconda3/lib/python3.6/runpy.py:125: RuntimeWarning: 'UBUVoiceAssistant.GUI.main' found in sys.modules after import of package 'UBUVoiceAssistant.GUI', but prior to execution of 'UBUVoiceAssistant.GUI.main'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Lang changed 1
Updating texts... Entrar
Updating texts... Entrar
```

Introduzco los datos:

```
Set reconnect time
Ya está actualizado.
Starting all mycroft-core services
Initializing...
Starting background service bus
CAUTION: The Mycroft bus is an open websocket with no built-in security
         measures.  You are responsible for protecting the local port
         8181 with a firewall as appropriate.
Starting background service enclosure
Launched Mycroft
=== ConnectionRefusedError(111, 'Conexión rehusada') ===
Traceback (most recent call last):
  File "/home/alvar/anaconda3/lib/python3.6/site-packages/websocket/_app.py", line 298, in run_forever
    proxy_type=proxy_type)
  File "/home/alvar/anaconda3/lib/python3.6/site-packages/websocket/_core.py", line 249, in connect
    options.pop('socket', None))
  File "/home/alvar/anaconda3/lib/python3.6/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/home/alvar/anaconda3/lib/python3.6/site-packages/websocket/_http.py", line 200, in _open_socket
    raise err
  File "/home/alvar/anaconda3/lib/python3.6/site-packages/websocket/_http.py", line 175, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Conexión rehusada
Set reconnect time
Message Bus Client will reconnect in 0 seconds.
Set reconnect time
```

Y se queda esperando eternamente:

![imagen](https://user-images.githubusercontent.com/16717649/125771570-e8ed17a5-ceec-4816-a180-10254f5f89a1.png)

**Comment by rogama25** [comment]
Tal y como se indica en el manual, la primera ejecución puede tardar hasta varios minutos (diría que 2-3 máximo). Esto se debe a que Mycroft por detrás está descargando componentes necesarios para ejecutarse. 

Los mensajes de la consola son completamente normales, ya que desde el cliente intento conectarme lo más pronto posible al backend, aunque no esté listo. Tras aparecer 3-4 veces deberían dejar de salir mensajes en la consola, al seleccionar español como idioma, se debería oír un "Espera mientras acabo de iniciarme, por favor" y tras un minuto saldrá la ventana de emparejamiento

**Comment by rogama25** [comment]
He hecho una instalación limpia de Linux Mint 20.2 Cinnamon (la última disponible actualmente) en una máquina virtual y me ha funcionado correctamente.

Acabo de revisar más en detalle los logs que pegaste @ubutfgm y creo haber visto el problema.
En tu traza se escoge por defecto el python que trae Anaconda (/home/alvar/anaconda3) y lo que me has comentado que no encontraba los paquetes es posible porque pip3, que es lo que uso para instalar algunos paquetes, haga referencia al ejecutable a nivel global. En mi traza salen los paquetes en una ruta del sistema: 
![image](https://user-images.githubusercontent.com/11318350/125968747-ffc26cf6-5dfe-4fc4-a8c0-073b586e0d83.png)

Con esto definitivamente no contaba al hacer la instalación, porque ninguna de las máquinas usaba Anaconda. Puede que lo consigas solucionando usando el `update-alternatives` de los comandos pip3 y python3 para usar los binarios `/usr/bin/python3` y `/usr/bin/pip3`. O, en caso de que no puedas solucionarlo así, quizá tengas que deshacer algún alias que estés usando para esos comandos.

Finalmente, la otra opción que tienes es usar una VM porque al usar Linux como host no creo que tengas algunos problemas que menciono en el manual cuando el host es un Windows 10 con Hyper-V
